# Generated by Django 4.1.7 on 2023-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', models.FloatField(max_length=15)),
                ('volume24', models.FloatField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
            ],
        ),
    ]
